apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: ramp-provider
    app.kubernetes.io/managed-by: kustomize
  name: ramp-provider-manager-metrics
spec:
  ports:
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    control-plane: ramp-provider
    app.kubernetes.io/name: ramp-provider
